In [ ]:
import numpy as np

a = np.array([0,1,2,3,4])
print(type(a)) # numpy.ndarray : numpy array
a.dtype
a.size
a.ndim
a.shape # size of array in each dimension

c = np.array([20,1,2,3,4])
c[0] = 100
c[4] = 9

# Slicing
d = c[1:4] # 1 2 3
print(d)

e = []  # a into c
for i in range(len(a)) :
  e.append(a[i]*c[i])
print(e)

# Vector Addition
u = np.array([1,0])
v = np.array([0,1])
# z = u+v
# print(z)

z = []
for n,m in zip(u,v):
  z.append(n+m)
print(z)
# zip(u, v) pairs corresponding elements from u and v together.

# Multiplication with scalar
p = np.array([1,2])
# r = 2*p
# print(r)

r = []
for n in p:
  r.append(2*n)
print(r)

# Assignment 4

# Q1

a = np.array([1,2,3,4,5])
print(a+2)
print(a*3)
print(a/2)

# Q2

arr = np.array([1,2,3,6,4,5])
reversed_arr = arr[::-1]
print(reversed_arr)

# b part
def most_frequent_value_with_indices(arr) :
  unique_values , counts = np.unique(arr,return_counts=True)

  most_frequent_value = unique_values[np.argmax(counts)]

  indices = np.where(arr==most_frequent_value)[0]
  return most_frequent_value,indices

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])

print("for x : ")
value , indices = most_frequent_value_with_indices(x)
print(f"Most frequent value : {value}, indices : {indices}")

print("for y : ")
value , indices = most_frequent_value_with_indices(y)
print(f"Most frequent value : {value}, indices : {indices}")

# Q3
# 0 based indexing
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0,1])
print(arr[2][0])


<class 'numpy.ndarray'>
[1 2 3]
[np.int64(0), np.int64(1), np.int64(4), np.int64(9), np.int64(36)]
[np.int64(1), np.int64(1)]
[np.int64(2), np.int64(4)]
[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]
[5 4 6 3 2 1]
for x : 
Most frequent value : 1, indices : [0 5 7 8 9]
for y : 
Most frequent value : 1, indices : [0 1 2]
20
70


In [ ]:
# Q4

import numpy as np

yourname = np.linspace(10,100,25)
print("array : ",yourname)
print("dimensions : ",yourname.ndim)
print("Shape : ",yourname.shape)
print("Total elemets : ",yourname.size)
print("data type : ",yourname.dtype)
print("Total bytes consumed : ",yourname.nbytes) # memory

transpose_array = yourname.reshape(25,1)
print(transpose_array)

transpose_T = yourname.T
# The .T attribute in NumPy is used to transpose an array.
# However, when used on a 1D array, it does nothing because a 1D array

if np.array_equal(transpose_array,transpose_T) :
  print("Both give same results")
else :
  print("T attribute does nothing to 1d array")

array :  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
dimensions :  1
Shape :  (25,)
Total elemets :  25
data type :  float64
Total bytes consumed :  200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
T attribute does nothing to 1d array


In [ ]:
# Q5

import numpy as np

ucs420_dhruv = np.array([
    [-10,20,30,40],
    [50,60,70,80],
    [90,15,20,35]
])

print("mean : ",np.mean(ucs420_dhruv))
print("Median : ",np.median(ucs420_dhruv))
print("Max : ",np.max(ucs420_dhruv))
print("Min : ",np.min(ucs420_dhruv))
print("Unique elements : ",np.unique(ucs420_dhruv))

# reshape() creates a new array without changing data.
# resize() modifies the original array, repeating or truncating data if needed.

reshaped_ucs420_dhruv = ucs420_dhruv.reshape(4,3)
print(reshaped_ucs420_dhruv)
print()
resized_ucs420_dhruv = np.resize(ucs420_dhruv,(2,3)) # This will modify the original array
print(resized_ucs420_dhruv)


mean :  41.666666666666664
Median :  37.5
Max :  90
Min :  -10
Unique elements :  [-10  15  20  30  35  40  50  60  70  80  90]
[[-10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [ 15  20  35]]

[[-10  20  30]
 [ 40  50  60]]
